sources:
  ols: [
    doid, 
    hp, 
    efo, 
    mesh, 
    ordo, 
    mondo, 
    go,
    chebi
    ]

  api:

    quickgo:
      version_func: quickgo
      base_url: https://www.ebi.ac.uk/QuickGO/services/
      operations: 
        - name: annotation/downloadSearch
          filename: "quickgo_annotations.gpad"
          params:
            taxonId: "9606"
            taxonUsage: "descendants"
          headers:
            Accept: text/gpad
  
    clinpgx:
      base_url: https://api.clinpgx.org/v1/download/file/data/
      operations:
        - name: relationships.zip
          filename: relationships.zip

        - name: summaryAnnotations.zip
          filename: summaryAnnotations.zip

        - name: variantAnnotations.zip
          filename: variantAnnotations.zip

        - name: guidelineAnnotations.json.zip
          filename: guidelineAnnotations.json.zip

        - name: drugLabels.zip
          filename: drugLabels.zip

        - name: pathways-tsv.zip
          filename: pathways-tsv.zip

        - name: clinicalVariants.zip
          filename: clinicalVariants.zip

        - name: occurrences.zip
          filename: occurrences.zip

        - name: variants.zip
          filename: variants.zip

        - name: drugs.zip
          filename: drugs.zip

        - name: chemicals.zip
          filename: chemicals.zip

        - name: phenotypes.zip
          filename: phenotypes.zip

    hgnc:
      version_func: hgnc
      base_url: https://storage.googleapis.com/public-download-files/
      operations:
        - name: 'hgnc/json/json/hgnc_complete_set.json'
          filename: hgnc_complete.json
  
  web:

    uniprot:
      version_func: UniProt
      pages:
        - web_page: https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/
          tag: a
          file_rules:
            extensions: ["dat.gz"]
            name_contains: ["trembl", "sprot"]
            name_contains_mode: or

    opentarget:
      version_func: OpenTargets
      pages:
        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/association_by_datasource_direct/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/association_by_datasource_indirect/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/association_by_datatype_direct/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/association_by_datatype_indirect/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/association_overall_direct/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/association_overall_indirect/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/biosample/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/colocalisation/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/credible_set/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/disease/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/disease_hpo/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/disease_phenotype/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/drug_indication/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/drug_mechanism_of_action/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/drug_molecule/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/drug_warning/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/enhancer_to_gene/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/evidence_chembl/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/evidence_reactome/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/expression/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/go/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/interaction/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/literature/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/mouse_phenotype/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/pharmacogenomics/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/reactome/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/study/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/target/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

        - web_page: https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/variant/
          tag: a
          file_rules:
            extensions: ["parquet"]
            name_contains: []

    chebi_sql:
      version_func: ChEBI_SQL
      pages:
        - web_page: https://ftp.ebi.ac.uk/pub/databases/chebi/generic_dumps/generic_dump_allstar/
          file_rules:
            extensions: ["sql.zip"]
            name_contains: []

    clinvar:
      version_func: clinvar
      pages:
        - web_page: https://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/
          file_rules:
            extensions: ["gz"]
            name_contains: ["variant_summary"]

    gwascatalog:
      version_func: gwas
      pages: 
        - web_page: https://ftp.ebi.ac.uk/pub/databases/gwas/releases/latest/
          file_rules:
            extensions: ["zip"]
            name_contains: ["ontology-annotated-full"]
            
    chembl:
      version_func: ChEMBLdb
      pages:
        - web_page: https://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/
          file_rules:
            extensions: ["tar.gz"]
            name_contains: ["chembl", "sqlite"]
            name_contains_mode: and

    markerdb:
      version_func: MarkerDB
      pages:
        - web_page: https://markerdb.ca/downloads
          tag: a
          file_rules:
            name_contains: [
              "download_all_proteins?format=xml",
              "download_all_chemicals?format=xml",
              "download_all_sequence_variants?format=xml",
              "download_all_karyotypes?format=xml",
              "download_all_diagnostic_chemicals?format=xml",
              "download_all_diagnostic_proteins?format=xml",
              "download_all_risk_genetics?format=xml",
              "download_all_exposure_chemicals?format=xml"
            ]
    
    protein_atlas:
      version_func: HPA
      pages:
        - web_page: https://www.proteinatlas.org/about/download
          tag: a
          file_rules:
            extensions: [xml.gz]
            name_contains: ["proteinatlas"]

        - web_page: https://www.proteinatlas.org/humanproteome/single+cell/single+cell+type/data#datasets
          tag: a
          file_rules:
            extensions: [zip]
            name_contains: ["rna_single_cell_type.tsv"]
        
        - web_page: https://www.proteinatlas.org/humanproteome/single+cell/immune+cell/data#immune_cells_hpa
          tag: a
          file_rules:
            extensions: [zip]
            name_contains: ["rna_immune_cell.tsv"]

        - web_page: https://www.proteinatlas.org/humanproteome/tissue/data#normal_tissues_ihc
          tag: a
          file_rules:
            extensions: [zip]
            name_contains: ["rna_tissue_consensus.tsv"]

    tiga:
      version_func: TIGA
      pages:
        - web_page: https://unmtid-dbs.net/download/TIGA/latest/
          tag: a
          file_rules:
            extensions: ["tsv"]
            name_contains: [
              "gene-trait_provenance",
              "gene-trait_stats"
            ]

    diseases:
      pages: 
        - web_page: https://diseases.jensenlab.org/Downloads
          tag: a
          file_rules:
            extensions: ["tsv"]
            name_contains: ["human_disease_knowledge_full"]

    drug_central:
      version_func: DrugCentral
      pages:
        - web_page: https://drugcentral.org/ActiveDownload
          tag: a
          file_rules:
            extensions: ["sql.gz"]
            name_contains: ["drugcentral"]

    food:
      version_func: FooDB
      pages:
        - web_page: https://foodb.ca/downloads
          tag: a
          file_rules:
            extensions: ["tar.gz"]
            name_contains: ["foodb", 
                            "mysql"]
            name_contains_mode: and

    wikipathways:
      pages:
        - web_page: https://www.wikipathways.org/json/index.html
          tag: a
          file_rules:
            extensions: [json]
            name_contains: ["findPathwaysByXref"]

  custom: [
    pathway_commons
  ]
 
  bioportal: [
    ICD10CM,
    ICD9CM
  ]